pub mod platforms {
    #[cfg(target_os = "ios")]
    pub mod ios;
    #[cfg(target_os = "macos")]
    pub mod macos;
}

pub mod widgets;

pub mod core {
    pub mod native_view;
}

// Re-export platform types for convenience
pub use makepad_platform::native_view::*;

// Re-export widgets
pub use widgets::*;

use makepad_draw::*;

/// Register live design for native components
pub fn live_design(cx: &mut Cx) {
    // Call the live_design function generated by the live_design! macro in switch.rs
    widgets::live_design(cx);
}

/// Initialize native view implementations
/// This should be called early in the app lifecycle to enable full native view functionality
pub fn init_native_views(cx: &mut Cx) {
    #[cfg(target_os = "macos")]
    {
        platforms::macos::init(cx);
    }
    #[cfg(target_os = "ios")]
    {
        platforms::ios::init(cx);
    }
}
