[package]
name = "makepad-shadecn-checkbox"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Shadecn Checkbox component for Makepad"

[dependencies]
makepad-shadecn-core = { path = "../../core", version = "0.1.0" }
makepad-draw = { path = "../../../draw", version = "1.0.0" }
makepad-derive-widget = { path = "../../../widgets/derive_widget", version = "1.0.0" }
makepad-widgets = { path = "../../../widgets", version = "1.0.0" }
